In [22]:
import torch
torch.empty(2,2)

tensor([[1.5554e-43, 1.5975e-43],
        [5.6052e-44, 1.2752e-43]])

In [23]:
torch.empty(3,3)

tensor([[7.0367e+22, 2.1715e-18, 6.7950e+22],
        [1.3520e+22, 1.0920e-05, 8.3092e+20],
        [1.3593e-43, 0.0000e+00, 7.4862e-13]])

In [24]:
torch.empty(2,2,2)

tensor([[[0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00],
         [0.0000e+00, 0.0000e+00]]])

In [25]:
torch.zeros(2,2,2)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [26]:
torch.ones(2,2,2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [29]:
torch.rand(2,2,2)

tensor([[[0.1784, 0.8238],
         [0.5557, 0.9770]],

        [[0.4440, 0.9478],
         [0.7445, 0.4892]]])

In [30]:
torch.manual_seed(100)
torch.rand(2,2,2)

tensor([[[0.1117, 0.8158],
         [0.2626, 0.4839]],

        [[0.6765, 0.7539],
         [0.2627, 0.0428]]])

In [31]:
x=torch.tensor([[1,2,3],[12,33,44]])
print(x)

tensor([[ 1,  2,  3],
        [12, 33, 44]])


In [32]:
print(x.shape)

torch.Size([2, 3])


In [33]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [34]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])